print("Welcome to the simple calculator")
print("This Calculator multiplies two numbers supplied by the user.")
num1 = input("Enter your first number")
num2 = input("Enter your second number")
print(int(num1) * int(num2))
